/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pikachu_master.User_Interface.Screens;

import com.mycompany.pikachu_master.Controller.GameConfig;
import com.mycompany.pikachu_master.User_Interface.Components.BackgroundMain;
import com.mycompany.pikachu_master.User_Interface.Components.BackgroundStartScreen;

/**
 *
 * @author laptop
 */
public class LevelScreen extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LevelScreen.class.getName());

    /**
     * Creates new form LevelScreen
     */
    
    StartScreen start;
    public LevelScreen(StartScreen start) {
        setContentPane(new BackgroundStartScreen());
        initComponents();
        this.setMinimumSize(new java.awt.Dimension(800, 600));
        this.start = start;
//        GameConfig Level = new GameConfig(ERROR, ABORT, HEIGHT);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        exitButton3 = new javax.swing.JButton();
        africaButton = new javax.swing.JButton();
        asianButton = new javax.swing.JButton();
        europeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        exitButton3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitButton3.setText("<");
        exitButton3.addActionListener(this::exitButton3ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        getContentPane().add(exitButton3, gridBagConstraints);

        africaButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        africaButton.setText("AFRICA");
        africaButton.setPreferredSize(new java.awt.Dimension(220, 50));
        africaButton.addActionListener(this::africaButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(240, 60, 270, 0);
        getContentPane().add(africaButton, gridBagConstraints);

        asianButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        asianButton.setText("ASIAN ");
        asianButton.setPreferredSize(new java.awt.Dimension(220, 50));
        asianButton.addActionListener(this::asianButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 141;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(240, 0, 270, 80);
        getContentPane().add(asianButton, gridBagConstraints);

        europeButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        europeButton.setText("EUROPE  ");
        europeButton.setPreferredSize(new java.awt.Dimension(220, 50));
        europeButton.addActionListener(this::europeButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 126;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(240, 0, 270, 0);
        getContentPane().add(europeButton, gridBagConstraints);

        setSize(new java.awt.Dimension(814, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton3ActionPerformed
        // TODO add your handling code here:
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitButton3ActionPerformed

    private void africaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_africaButtonActionPerformed
        // TODO add your handling code here:
        start.setLevel("AFRICA");
        start.UpdateLevel("AFRICA");
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_africaButtonActionPerformed

    private void asianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asianButtonActionPerformed
        // TODO add your handling code here:
        start.setLevel("ASIAN");
        start.UpdateLevel("ASIAN");
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_asianButtonActionPerformed

    private void europeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_europeButtonActionPerformed
        // TODO add your handling code here:
        start.setLevel("EUROPE");
        start.UpdateLevel("EUROPE");
        start.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_europeButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new LevelScreen().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton africaButton;
    private javax.swing.JButton asianButton;
    private javax.swing.JButton europeButton;
    private javax.swing.JButton exitButton3;
    // End of variables declaration//GEN-END:variables
}
