/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pikachu_master.User_Interface.Screens;

import com.mycompany.pikachu_master.Controller.GameConfig;
import com.mycompany.pikachu_master.Controller.PlayScreen;
import com.mycompany.pikachu_master.User_Interface.Components.BackgroundMain;
import com.mycompany.pikachu_master.User_Interface.Components.BackgroundStartScreen;
import java.awt.event.ComponentEvent;

/**
 *
 * @author laptop
 */
public class MainScreen extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainScreen.class.getName());

    /**
     * Creates new form MainScreen
     *
     * @param config
     */
    GameConfig config;
    PlayScreen gameBoard;

    public MainScreen(GameConfig config) {
        this.config = config;
        setContentPane(new BackgroundStartScreen());
        initComponents();

        gameBoard = new PlayScreen(config);

        // Khởi tạo bàn cờ
        //gameBoard.setPreferredSize(new java.awt.Dimension(700, 450));
        // SỬA TẠI ĐÂY: Thay vì BorderLayout, hãy dùng AbsoluteConstraints
        // Tham số: (x, y, width, height) - Điều chỉnh số này để khớp với ảnh nền của em
        this.getContentPane().add(gameBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 700, 450));
        //this.getContentPane().setLayout(new java.awt.GridBagLayout());
        //this.getContentPane().add(gameBoard);

        //căn chỉnh vị trí.
        this.addComponentListener(new java.awt.event.ComponentAdapter() {
            @Override
            public void componentResized(java.awt.event.ComponentEvent evt) {
                int screenWidth = getContentPane().getWidth();
                int screenHeight = getContentPane().getHeight();

                int boardWidth = 700;
                int boardHeight = 450;

                int newX = (screenWidth - boardWidth) / 2;

                int newY = ((screenHeight - 80) - boardHeight) / 2 + 80;

                if (newX < 0) {
                    newX = 0;
                }
                if (newY < 80) {
                    newY = 80;
                }

                getContentPane().add(gameBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(newX, newY, boardWidth, boardHeight));
                int topBarX = (screenWidth - topBarPanel.getWidth()) / 2;
                if (topBarX < 0) {
                    topBarX = 0;
                }
                getContentPane().add(topBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(topBarX, 10, topBarPanel.getWidth(), topBarPanel.getHeight()));
                // --------------------------------------------------

                getContentPane().revalidate();
            }
        });

        this.revalidate();
        this.repaint();
    }

    // xử lý resert lại game mới.
    public void resertGame(GameConfig newConfig) {
        this.config = newConfig;

        int currentX = gameBoard.getX();
        int currentY = gameBoard.getY();

        //xóa bảng hiện tại.
        this.getContentPane().remove(gameBoard);
        // tạo bảng mới.
        gameBoard = new PlayScreen(config);

        //this.getContentPane().add(gameBoard);
        this.getContentPane().add(gameBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(currentX, currentY, 700, 450));
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        topBarPanel = new javax.swing.JPanel();
        coin = new javax.swing.JLabel();
        levelLabel = new javax.swing.JLabel();
        level_point = new javax.swing.JLabel();
        PointLabel = new javax.swing.JLabel();
        point = new javax.swing.JLabel();
        Timeline = new javax.swing.JSlider();
        swapButton = new javax.swing.JButton();
        timeButton = new javax.swing.JButton();
        hintButton = new javax.swing.JButton();
        coinLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        settingmainButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topBarPanel.setOpaque(false);
        topBarPanel.setPreferredSize(new java.awt.Dimension(800, 80));
        topBarPanel.setLayout(new java.awt.GridBagLayout());

        coin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coin.setText("VÀNG:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 16, 30, 0);
        topBarPanel.add(coin, gridBagConstraints);

        levelLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        levelLabel.setText("CẤP ĐỘ: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 30, 0);
        topBarPanel.add(levelLabel, gridBagConstraints);

        level_point.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        level_point.setText("12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 8, 30, 0);
        topBarPanel.add(level_point, gridBagConstraints);

        PointLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PointLabel.setText("ĐIỂM:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 30, 30, 0);
        topBarPanel.add(PointLabel, gridBagConstraints);

        point.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        point.setText("110");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 30, 0);
        topBarPanel.add(point, gridBagConstraints);

        Timeline.setBackground(new java.awt.Color(204, 204, 204));
        Timeline.setToolTipText("");
        Timeline.setPreferredSize(new java.awt.Dimension(200, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 204;
        gridBagConstraints.ipady = -10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 38, 30, 0);
        topBarPanel.add(Timeline, gridBagConstraints);

        swapButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 10)); // NOI18N
        swapButton.setText("🔁");
        swapButton.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 30, 0);
        topBarPanel.add(swapButton, gridBagConstraints);

        timeButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 12)); // NOI18N
        timeButton.setPreferredSize(new java.awt.Dimension(30, 30));
        timeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeButtonMouseClicked(evt);
            }
        });
        timeButton.addActionListener(this::timeButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 30, 0);
        topBarPanel.add(timeButton, gridBagConstraints);

        hintButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 16)); // NOI18N
        hintButton.setText("🔍");
        hintButton.setPreferredSize(new java.awt.Dimension(30, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 30, 0);
        topBarPanel.add(hintButton, gridBagConstraints);

        coinLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        coinLabel.setText("9999");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 4, 30, 0);
        topBarPanel.add(coinLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 260;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 34, 0, 0);
        topBarPanel.add(jLabel1, gridBagConstraints);

        settingmainButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 20)); // NOI18N
        settingmainButton.setText("⚙");
        settingmainButton.setAlignmentY(0.0F);
        settingmainButton.setPreferredSize(new java.awt.Dimension(45, 45));
        settingmainButton.addActionListener(this::settingmainButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 12;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 30, 20);
        topBarPanel.add(settingmainButton, gridBagConstraints);

        getContentPane().add(topBarPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(9999, 3));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, -1, -1));

        setSize(new java.awt.Dimension(814, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void settingmainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingmainButtonActionPerformed
        // TODO add your handling code here:
        //Pause Setting = new Pause();
        Pause pause = new Pause(this,config);
        pause.setVisible(true);
        // this.dispose();
    }//GEN-LAST:event_settingmainButtonActionPerformed

    private void timeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeButtonActionPerformed

    private void timeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_timeButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
//        GameConfig config = new GameConfig(6, 5, 12);

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> new MainScreen(config).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PointLabel;
    private javax.swing.JSlider Timeline;
    private javax.swing.JLabel coin;
    private javax.swing.JLabel coinLabel;
    private javax.swing.JButton hintButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JLabel level_point;
    private javax.swing.JLabel point;
    private javax.swing.JButton settingmainButton;
    private javax.swing.JButton swapButton;
    private javax.swing.JButton timeButton;
    private javax.swing.JPanel topBarPanel;
    // End of variables declaration//GEN-END:variables
}
