/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.pikachu_master.User_Interface.Screens;

import com.mycompany.pikachu_master.Controller.GameConfig;
import com.mycompany.pikachu_master.Controller.PlayScreen;
import com.mycompany.pikachu_master.User_Interface.Components.BackgroundPause;

/**
 *
 * @author laptop
 */
public class Pause extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pause.class.getName());

    /**
     * Creates new form setting
     */
    
    MainScreen main;
    GameConfig config;
    
    public Pause(MainScreen main, GameConfig config) {
        setContentPane(new BackgroundPause());
        initComponents();
        this.main = main;
        this.config = config;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        Choi_tiep = new javax.swing.JButton();
        Van_moi = new javax.swing.JButton();
        instructionButton1 = new javax.swing.JButton();
        exitmenuButton = new javax.swing.JButton();
        volumnButton = new javax.swing.JToggleButton();
        soundButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        Choi_tiep.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Choi_tiep.setText("CHƠI TIẾP");
        Choi_tiep.setPreferredSize(new java.awt.Dimension(250, 40));
        Choi_tiep.addActionListener(this::Choi_tiepActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 150;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(100, 26, 0, 24);
        getContentPane().add(Choi_tiep, gridBagConstraints);

        Van_moi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Van_moi.setText("VÁN MỚI");
        Van_moi.setPreferredSize(new java.awt.Dimension(250, 40));
        Van_moi.addActionListener(this::Van_moiActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 24);
        getContentPane().add(Van_moi, gridBagConstraints);

        instructionButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        instructionButton1.setText("HƯỚNG DẪN");
        instructionButton1.setPreferredSize(new java.awt.Dimension(250, 40));
        instructionButton1.addActionListener(this::instructionButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 129;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 24);
        getContentPane().add(instructionButton1, gridBagConstraints);

        exitmenuButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitmenuButton.setText("MÀN HÌNH CHÍNH");
        exitmenuButton.setPreferredSize(new java.awt.Dimension(250, 40));
        exitmenuButton.addActionListener(this::exitmenuButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.ipady = 13;
        gridBagConstraints.insets = new java.awt.Insets(0, 26, 0, 24);
        getContentPane().add(exitmenuButton, gridBagConstraints);

        volumnButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        volumnButton.setText("🎧");
        volumnButton.setPreferredSize(new java.awt.Dimension(122, 40));
        volumnButton.setRolloverEnabled(false);
        volumnButton.addActionListener(this::volumnButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(6, 3, 94, 24);
        getContentPane().add(volumnButton, gridBagConstraints);

        soundButton.setFont(new java.awt.Font("Segoe UI Emoji", 0, 18)); // NOI18N
        soundButton.setText("🔊");
        soundButton.setMaximumSize(new java.awt.Dimension(125, 40));
        soundButton.setPreferredSize(new java.awt.Dimension(122, 40));
        soundButton.setRolloverEnabled(false);
        soundButton.addActionListener(this::soundButtonActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 91;
        gridBagConstraints.ipady = 12;
        gridBagConstraints.insets = new java.awt.Insets(6, 26, 94, 3);
        getContentPane().add(soundButton, gridBagConstraints);

        setSize(new java.awt.Dimension(314, 408));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void volumnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volumnButtonActionPerformed
        // TODO add your handling code here:
        if (volumnButton.isSelected()) {
            volumnButton.setText("🚫");
        } else {
            volumnButton.setText("🎧");
        }
    }//GEN-LAST:event_volumnButtonActionPerformed

    private void Choi_tiepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Choi_tiepActionPerformed
        // TODO add your handling code here:    
        this.setVisible(false);
    }//GEN-LAST:event_Choi_tiepActionPerformed

    private void Van_moiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Van_moiActionPerformed
        // TODO add your handling code here:
//        GameConfig config = new GameConfig(6, 5,0);
        main.resertGame(config);
        this.dispose();
    }//GEN-LAST:event_Van_moiActionPerformed

    private void exitmenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenuButtonActionPerformed
        // TODO add your handling code here:
        StartScreen pika = new StartScreen();
        pika.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exitmenuButtonActionPerformed

    private void instructionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionButton1ActionPerformed
        // TODO add your handling code here:
       // HelpScreen instruct = new HelpScreen();
        //instruct.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_instructionButton1ActionPerformed

    private void soundButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_soundButtonActionPerformed
        // TODO add your handling code here:                                          
        if (soundButton.isSelected()) {
            soundButton.setText("🔇");
        } else {
            soundButton.setText("🔊");
        }
    }//GEN-LAST:event_soundButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(() -> new Pause().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Choi_tiep;
    private javax.swing.JButton Van_moi;
    private javax.swing.JButton exitmenuButton;
    private javax.swing.JButton instructionButton1;
    private javax.swing.JToggleButton soundButton;
    private javax.swing.JToggleButton volumnButton;
    // End of variables declaration//GEN-END:variables
}
